[metadata]
name = fnc
version = 0.1.0
license = MIT License

[options]
packages = find:
install_requires =
    torch>=2.2
    numpy
    omegaconf
    typer
    loguru
    tqdm

[options.entry_points]
console_scripts =
    fnc-generate = fnc.inference.generate:main
    fnc-serve = fnc.inference.serve:main
