"""Optional integration with a local Ollama server for richer hints."""
from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass
from typing import Optional


@dataclass
class OllamaBridge:
    """Lightweight wrapper that queries a local Ollama model when available."""

    model: Optional[str] = None
    timeout: float = 4.0

    def available(self) -> bool:
        return bool(self.model and self.model.strip())

    def suggest_summary(self, prompt: str) -> Optional[str]:
        """Return a short summary generated by Ollama, if possible."""

        if not self.available():
            return None
        command = [
            "ollama",
            "run",
            self.model.strip(),
            "--prompt",
            (
                "Provide a concise one-sentence summary of the user's message so "
                "I can mirror their intent. Keep it under 60 words and avoid role play.\n" + prompt
            ),
        ]
        try:
            result = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
                timeout=self.timeout,
            )
        except (FileNotFoundError, subprocess.SubprocessError, subprocess.TimeoutExpired):
            return None
        output = result.stdout.strip()
        if not output:
            return None
        # Some Ollama models stream JSON; try to decode line by line but fall back to raw text.
        for line in output.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith("{") and stripped.endswith("}"):
                try:
                    payload = json.loads(stripped)
                except json.JSONDecodeError:
                    continue
                content = payload.get("response") or payload.get("content")
                if content:
                    return content.strip()
            else:
                return stripped[:320]
        return None
